### ISSUE TITLE
Doubt - Parallel binning

### ISSUE THREAD

**Issue by FelipeMSD** [psj1997/SemiBin_tutorial_from_scratch#2]
Dear Pedro,

I've been testing SemiBin2 multi_easy_bin and I understood, based on the log it generates after binning, after concatenating the assemblies and mapping each fastq file to that it does not matter much if I run the binning command for all samples at the same time like this:

Option 1. `SemiBin2 multi_easy_bin -i /assembly_folder/concatenated.fa -b /alignemtns_folder/* -o /out_folder/`

Or sample by sample, like this:

Option 2. `SemiBin2 multi_easy_bin -i /assembly_folder/concatenated.fa -b /alignemtns_folder/${sample} -o /out_folder/`

Is that right? Or running all samples at once is important for training the algorithm?

I'm asking that because I would love to work with Option 2 for parallelisation purposes.

Thank you very much,
Felipe

**Comment by luispedro** [comment]
Hi. I'm not sure whether this is still relevant (sorry, I don't typically look at this repository so often and August was holiday time)

The short answer is that you can use the _advanced binning_ workflows at https://semibin.readthedocs.io/en/latest/usage/ instead of `multi_easy_bin` to get parallelization.

For this type of query, the mailing list is probably the best venue:
https://groups.google.com/g/semibin-users
